### PR TITLE
Update oidc to support new registration

### PR DESCRIPTION
**Pull request by PhilCorney**
ref: [Issue 86](https://github.com/spiffe/spire-tutorials/issues/86)
Updated oidc registration.

### CODE REVIEW

**Review by azdagron — DISMISSED** [review]
Thanks, @PhilCorney !

**Comment by azdagron** [comment]
Looks like we need DCO signoff on your commit....

**Comment by PhilCorney** [comment]
Hi @azdagron ,
Is there anything outstanding for approving the change?
Thanks
Phil

**Review by azdagron — APPROVED** [review]
Nope, thanks for following up, @PhilCorney !

**Pull request merged**
