### PR TITLE
Create docker-compose directory

### PR DESCRIPTION
**Pull request by lucianozablocki**
- Add tests for docker-compose to Travis
- Add path to existing scripts to be executed from _spire-tutorials_ directory
- Add script to execute all existing tests

Solves #49

### CODE REVIEW

**Review by sanderson042 — COMMENTED** [review]
Hi @lucianozablocki 👋  - Here's some comments. Ping me by Slack or reply here if you have questions. Cc: @Andres-GC 

# General comments

1. The spire-tutorials/README.md file should be updated with the new subdirectories for the three Docker Compose tutorials.
2. I'm not sure the purpose of the test-all.sh script. Could you put a comment in the docker-compose/test-all.sh file that says what it is for? This could be confusing for users who clone the repo. I mostly want to know if I should try running it myself or if this is only for Travis.
3. (This item is not valid if test-all.sh is not meant to be run interactively:) When I do run the test-all.sh script in a terminal window on macOS, some of the output gets staggered and my terminal window is screwed up (maybe control character output or missing newlines?). Sample output:
```
Removing network nested-spire_default
                                     Cleaning completed.
                                                        "nested-spire" test failed
                                                                                  There were test failures.
```

# Nested SPIRE tutorial

The directory paths in .../nested-spire/README.md need to be updated in a few places to show the new docker-compose directory:

1. "Prerequisites" section - first sentence. Change "...in the nested-spire directory" to "in the docker-compose/nested-spire directory".
2. "Create a Shared Directory" section, second paragraph.
3. Also, do users need to create the sharedRootSocket directory in this section? It seems like the script may do that.
4. "Run the Scenario" section - second paragraph.

I could not run the Nested SPIRE Docker Compose tutorial successfully. I get this timeout when I run the set-env.sh command:
```
[2020-12-16T01:47:14Z] Checking registration entry is propagated...
[2020-12-16T01:48:01Z] timed out waiting for the entry to be progagated to the agent
```

The next command fails like this:
```
/Users/steve/Documents/github-repos/spire-tutorials/docker-compose/nested-spire$ bash scripts/create-workload-registration-entries.sh
[2020-12-16T01:50:29Z] creating nestedA workload registration entry...
Error opening Certificate /Users/steve/Documents/github-repos/spire-tutorials/docker-compose/nested-spire/nestedA/agent/agent.crt.pem
4536129132:error:02FFF002:system library:func(4095):No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/crypto/bio/bss_file.c:255:fopen('/Users/steve/Documents/github-repos/spire-tutorials/docker-compose/nested-spire/nestedA/agent/agent.crt.pem', 'r')
4536129132:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/crypto/bio/bss_file.c:257:
unable to load certificate
ERROR: No container found for nestedA-server_1
```
I'm using this version of go:
go: stable 1.15.5 (bottled), HEAD

# Metrics tutorial

Some of the same directory paths need to be updated as in the Nested SPIRE tutorial. Search for "spire-tutorials" to find these areas.

I tried running the metrics tutorial but I could not get the metrics to display in Prometheus and Graphite using the paths/tokens in the sample images.

# Federation tutorial

Some of the same directory paths need to be updated as in the Nested SPIRE tutorial. Search for "spire-tutorials" to find these areas.

I successfully ran the Federation Docker Compose tutorial.

**Comment by lucianozablocki** [comment]
Hi @sanderson042 and thank you for the review!
I completely forgot about the updates in the _README's_ related to the new directory creation. I will change the docs wherever it is necessary.

### General comments
>2. I'm not sure the purpose of the test-all.sh script. Could you put a comment in the docker-compose/test-all.sh file that says what it is for? This could be confusing for users who clone the repo. I mostly want to know if I should try running it myself or if this is only for Travis.

The main purpose of the script is to run all the existing _docker-compose_ tests on Travis side, with every build (from #49, we can see that these tests were not executed). It is worth to note that this is the approach that it is currently used for _k8s_ tutorials and examples (for instance, see https://github.com/spiffe/spire-tutorials/blob/master/k8s/test-all.sh). Also, you can execute the script interactively, if you wish to, so both options are valid. 

>3. (This item is not valid if test-all.sh is not meant to be run interactively:) When I do run the test-all.sh script in a terminal window on macOS, some of the output gets staggered and my terminal window is screwed up (maybe control character output or missing newlines?).

Will try to fix it, as it is a known docker-compose bug (docker/compose#4910)

### Nested SPIRE tutorial

>3. Also, do users need to create the sharedRootSocket directory in this section? It seems like the script may do that.

If a user wishes to run the tutorial, it should follow all the steps described in the corresponding _README_, and that includes the creation of the _sharedRootSocket_ directory. But that doesn't mean that we shouldn't include this step on the test (that's executed by Travis). Following this reasoning, there will be an intentional overlapping between the steps detailed in the _README_, and those followed by the test (because, after all, the test actually sets the environment as desired, runs the tutorial and checks if everything goes as expected)

>I could not run the Nested SPIRE Docker Compose tutorial successfully. I get this timeout when I run the set-env.sh command:

We faced a similar issue while testing the tutorials, can you check if this is not related to docker pull rate limits?

### Metrics tutorial

>I tried running the metrics tutorial but I could not get the metrics to display in Prometheus and Graphite using the paths/tokens in the sample images.

Will check again if this tutorial executes correctly.

**Comment by sanderson042** [comment]
Hi @lucianozablocki - Thanks for the responses. Here are my replies:

> I completely forgot about the updates in the _README's_ related to the new directory creation. I will change the docs wherever it is necessary.

Sounds good, thanks!

> ### General comments
> The main purpose of the script is to run all the existing _docker-compose_ tests on Travis side, with every build (from #49, we can see that these tests were not executed). It is worth to note that this is the approach that it is currently used for _k8s_ tutorials and examples (for instance, see https://github.com/spiffe/spire-tutorials/blob/master/k8s/test-all.sh). Also, you can execute the script interactively, if you wish to, so both options are valid.

Thanks for explaining that. I guess a typical user might be able to read the shell scripts and understand the purpose, but just to make it easy, could we add some comments to the top of each test-all.sh file like this:
```
#!/bin/bash
# This script runs the test.sh script in each subdirectory to test if each
# tutorial is working properly. It is run by the Travis CI tool when a PR
# is submitted or merged on GitHub, but you can also run it interactively.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
...
```
You're right, the test-all.sh script is already in the k8s directory, so that file could be updated, too. 

> > 1. (This item is not valid if test-all.sh is not meant to be run interactively:) When I do run the test-all.sh script in a terminal window on macOS, some of the output gets staggered and my terminal window is screwed up (maybe control character output or missing newlines?).
> 
> Will try to fix it, as it is a known docker-compose bug ([docker/compose#4910](https://github.com/docker/compose/issues/4910))

Ok, I understand we may not be able to fix it. I had to run "stty sane" in my terminal to get it back to normal :-).

> ### Nested SPIRE tutorial
> > 1. Also, do users need to create the sharedRootSocket directory in this section? It seems like the script may do that.
> 
> If a user wishes to run the tutorial, it should follow all the steps described in the corresponding _README_, and that includes the creation of the _sharedRootSocket_ directory. But that doesn't mean that we shouldn't include this step on the test (that's executed by Travis). Following this reasoning, there will be an intentional overlapping between the steps detailed in the _README_, and those followed by the test (because, after all, the test actually sets the environment as desired, runs the tutorial and checks if everything goes as expected)

Sorry, I wasn't referring to the test-all.sh script, I mean the set-env.sh script described in the README seems to create that directory, so it seems like the README doesn't need to tell users to do it:
```
# create a shared folder for root agent socket to be accessed by nestedA and nestedB servers
mkdir -p "${PARENT_DIR}"/sharedRootSocket
```

> > I could not run the Nested SPIRE Docker Compose tutorial successfully. I get this timeout when I run the set-env.sh command:
> 
> We faced a similar issue while testing the tutorials, can you check if this is not related to docker pull rate limits?

I checked my docker pull rate limit and it was 99 available out of 100. I ran set-env.sh again and got the same timeout.

> ### Metrics tutorial
> > I tried running the metrics tutorial but I could not get the metrics to display in Prometheus and Graphite using the paths/tokens in the sample images.
> 
> Will check again if this tutorial executes correctly.

Ok.

**Comment by lucianozablocki** [comment]
> > ### General comments
> > The main purpose of the script is to run all the existing _docker-compose_ tests on Travis side, with every build (from #49, we can see that these tests were not executed). It is worth to note that this is the approach that it is currently used for _k8s_ tutorials and examples (for instance, see https://github.com/spiffe/spire-tutorials/blob/master/k8s/test-all.sh). Also, you can execute the script interactively, if you wish to, so both options are valid.
> 
> Thanks for explaining that. I guess a typical user might be able to read the shell scripts and understand the purpose, but just to make it easy, could we add some comments to the top of each test-all.sh file like this:

You're right about that, I'll add that comment to both _test-all.sh_ scripts, I think that it would be more self-explanatory for a user that's cloning the repo for the first time.

> > > 1. (This item is not valid if test-all.sh is not meant to be run interactively:) When I do run the test-all.sh script in a terminal window on macOS, some of the output gets staggered and my terminal window is screwed up (maybe control character output or missing newlines?).
> > 
> > 
> > Will try to fix it, as it is a known docker-compose bug ([docker/compose#4910](https://github.com/docker/compose/issues/4910))
> 
> Ok, I understand we may not be able to fix it. I had to run "stty sane" in my terminal to get it back to normal :-).

Didn't know about that quick-fix. I'll use it so I don't have to reopen the terminal everytime I run the script !

> > ### Nested SPIRE tutorial
> > > 1. Also, do users need to create the sharedRootSocket directory in this section? It seems like the script may do that.
> > 
> > 
> > If a user wishes to run the tutorial, it should follow all the steps described in the corresponding _README_, and that includes the creation of the _sharedRootSocket_ directory. But that doesn't mean that we shouldn't include this step on the test (that's executed by Travis). Following this reasoning, there will be an intentional overlapping between the steps detailed in the _README_, and those followed by the test (because, after all, the test actually sets the environment as desired, runs the tutorial and checks if everything goes as expected)
> 
> Sorry, I wasn't referring to the test-all.sh script, I mean the set-env.sh script described in the README seems to create that directory, so it seems like the README doesn't need to tell users to do it:

Oh, I misunderstand your comment! In that case, as neither that step nor any of the described steps are actually followed by a user (all of these are embedded into _set-env.sh_ script), I think that a possible solution is to add a note that explains this situation (similar to what's explained in the _Note_ section of https://github.com/spiffe/spire-tutorials/blob/master/k8s/envoy-opa/README.md#prerequisites). What do you think?

> > > I could not run the Nested SPIRE Docker Compose tutorial successfully. I get this timeout when I run the set-env.sh command:
> > 
> > 
> > We faced a similar issue while testing the tutorials, can you check if this is not related to docker pull rate limits?
> 
> I checked my docker pull rate limit and it was 99 available out of 100. I ran set-env.sh again and got the same timeout.

Ok, so we can discard that as a cause of the issue. Will check _nested SPIRE_ and _metrics_ tutorials.

**Comment by sanderson042** [comment]
Hi @lucianozablocki 👋  -

> > > ### Nested SPIRE tutorial
> > > > 1. Also, do users need to create the sharedRootSocket directory in this section? It seems like the script may do that.
> > > 
> > > 
> > > If a user wishes to run the tutorial, it should follow all the steps described in the corresponding _README_, and that includes the creation of the _sharedRootSocket_ directory. But that doesn't mean that we shouldn't include this step on the test (that's executed by Travis). Following this reasoning, there will be an intentional overlapping between the steps detailed in the _README_, and those followed by the test (because, after all, the test actually sets the environment as desired, runs the tutorial and checks if everything goes as expected)
> > 
> > 
> > Sorry, I wasn't referring to the test-all.sh script, I mean the set-env.sh script described in the README seems to create that directory, so it seems like the README doesn't need to tell users to do it:
> 
> Oh, I misunderstand your comment! In that case, as neither that step nor any of the described steps are actually followed by a user (all of these are embedded into _set-env.sh_ script), I think that a possible solution is to add a note that explains this situation (similar to what's explained in the _Note_ section of https://github.com/spiffe/spire-tutorials/blob/master/k8s/envoy-opa/README.md#prerequisites). What do you think?

Mainly I think we should remove the "Create a Shared Directory" section, or change it to just describe what the sharedRootSocket directory is used for. Adding the note from the envoy-opa tutorial is also useful. We should check if @Andres-GC agrees with these changes.

> > > > I could not run the Nested SPIRE Docker Compose tutorial successfully. I get this timeout when I run the set-env.sh command:
> > > 
> > > 
> > > We faced a similar issue while testing the tutorials, can you check if this is not related to docker pull rate limits?
> > 
> > 
> > I checked my docker pull rate limit and it was 99 available out of 100. I ran set-env.sh again and got the same timeout.
> 
> Ok, so we can discard that as a cause of the issue. Will check _nested SPIRE_ and _metrics_ tutorials.

I agree with what you said in a meeting today: if there are problems running those tutorials we should deal with them in a separate bug and PR, assuming the changes here did not cause those problems.

**Comment by Andres-GC** [comment]
> Hi @lucianozablocki  -
> 
> > > > ### Nested SPIRE tutorial
> > > > > 1. Also, do users need to create the sharedRootSocket directory in this section? It seems like the script may do that.
> > > > 
> > > > 
> > > > If a user wishes to run the tutorial, it should follow all the steps described in the corresponding _README_, and that includes the creation of the _sharedRootSocket_ directory. But that doesn't mean that we shouldn't include this step on the test (that's executed by Travis). Following this reasoning, there will be an intentional overlapping between the steps detailed in the _README_, and those followed by the test (because, after all, the test actually sets the environment as desired, runs the tutorial and checks if everything goes as expected)
> > > 
> > > 
> > > Sorry, I wasn't referring to the test-all.sh script, I mean the set-env.sh script described in the README seems to create that directory, so it seems like the README doesn't need to tell users to do it:
> > 
> > 
> > Oh, I misunderstand your comment! In that case, as neither that step nor any of the described steps are actually followed by a user (all of these are embedded into _set-env.sh_ script), I think that a possible solution is to add a note that explains this situation (similar to what's explained in the _Note_ section of https://github.com/spiffe/spire-tutorials/blob/master/k8s/envoy-opa/README.md#prerequisites). What do you think?
> 
> Mainly I think we should remove the "Create a Shared Directory" section, or change it to just describe what the sharedRootSocket directory is used for. Adding the note from the envoy-opa tutorial is also useful. We should check if @Andres-GC agrees with these changes.

Hi Steve/Luciano.
The section [Create a Shared Directory](https://github.com/spiffe/spire-tutorials/tree/master/nested-spire#create-a-shared-directory) describes a key point of the configuration. As mentioned there:
 `create a local directory that will be volume mounted on the services to share the Workload API between the root SPIRE Agent and its nested SPIRE Servers.`
Using the shared directory is the way that allows  different deployments of SPIRE to be chained.

So, from my side I think we should include it as part of the README.md file.
I like the option proposed by Luciano of adding a note as we already did on a different tutorial. At the end, in all tutorials we have the same situation: the README.md file explains and describe all the steps but the readers don't need to create any of them, everything is provide by the tutorial and run using the Bash scripts.

**Comment by sanderson042** [comment]
Hi @Andres-GC 

> > > Oh, I misunderstand your comment! In that case, as neither that step nor any of the described steps are actually followed by a user (all of these are embedded into _set-env.sh_ script), I think that a possible solution is to add a note that explains this situation (similar to what's explained in the _Note_ section of https://github.com/spiffe/spire-tutorials/blob/master/k8s/envoy-opa/README.md#prerequisites). What do you think?
> > 
> > 
> > Mainly I think we should remove the "Create a Shared Directory" section, or change it to just describe what the sharedRootSocket directory is used for. Adding the note from the envoy-opa tutorial is also useful. We should check if @Andres-GC agrees with these changes.
> 
> Hi Steve/Luciano.
> The section [Create a Shared Directory](https://github.com/spiffe/spire-tutorials/tree/master/nested-spire#create-a-shared-directory) describes a key point of the configuration. As mentioned there:
> `create a local directory that will be volume mounted on the services to share the Workload API between the root SPIRE Agent and its nested SPIRE Servers.`
> Using the shared directory is the way that allows different deployments of SPIRE to be chained.
> 
> So, from my side I think we should include it as part of the README.md file.
> I like the option proposed by Luciano of adding a note as we already did on a different tutorial. At the end, in all tutorials we have the same situation: the README.md file explains and describe all the steps but the readers don't need to create any of them, everything is provide by the tutorial and run using the Bash scripts.

Sorry I am causing this scope creep from the original PR--I didn't notice this before. I agree with you guys about adding the note. But what is a little confusing to me is that you are putting in the exact steps to make the directory (cd nested-spire;    mkdir sharedRootSocket). Maybe just change it to say where the directory is needed? Here's a new proposed version of that section. If you don't agree, we can leave it unchanged.

## Create a Shared Directory

The first thing needed is a local directory that will be volume mounted on the services to share the Workload API between the root SPIRE Agent and its nested SPIRE Servers. This tutorial uses 
`.../spire-tutorials/docker-compose/nested-spire/sharedRootSocket`as the shared directory.

**Comment by Andres-GC** [comment]
> Hi @Andres-GC
> 
> > > > Oh, I misunderstand your comment! In that case, as neither that step nor any of the described steps are actually followed by a user (all of these are embedded into _set-env.sh_ script), I think that a possible solution is to add a note that explains this situation (similar to what's explained in the _Note_ section of https://github.com/spiffe/spire-tutorials/blob/master/k8s/envoy-opa/README.md#prerequisites). What do you think?
> > > 
> > > 
> > > Mainly I think we should remove the "Create a Shared Directory" section, or change it to just describe what the sharedRootSocket directory is used for. Adding the note from the envoy-opa tutorial is also useful. We should check if @Andres-GC agrees with these changes.
> > 
> > 
> > Hi Steve/Luciano.
> > The section [Create a Shared Directory](https://github.com/spiffe/spire-tutorials/tree/master/nested-spire#create-a-shared-directory) describes a key point of the configuration. As mentioned there:
> > `create a local directory that will be volume mounted on the services to share the Workload API between the root SPIRE Agent and its nested SPIRE Servers.`
> > Using the shared directory is the way that allows different deployments of SPIRE to be chained.
> > So, from my side I think we should include it as part of the README.md file.
> > I like the option proposed by Luciano of adding a note as we already did on a different tutorial. At the end, in all tutorials we have the same situation: the README.md file explains and describe all the steps but the readers don't need to create any of them, everything is provide by the tutorial and run using the Bash scripts.
> 
> Sorry I am causing this scope creep from the original PR--I didn't notice this before. I agree with you guys about adding the note. But what is a little confusing to me is that you are putting in the exact steps to make the directory (cd nested-spire; mkdir sharedRootSocket). Maybe just change it to say where the directory is needed? Here's a new proposed version of that section. If you don't agree, we can leave it unchanged.
> 
> ## Create a Shared Directory
> The first thing needed is a local directory that will be volume mounted on the services to share the Workload API between the root SPIRE Agent and its nested SPIRE Servers. This tutorial uses
> `.../spire-tutorials/docker-compose/nested-spire/sharedRootSocket`as the shared directory.

I like that.

**Comment by lucianozablocki** [comment]
Hello @sanderson042 and @Andres-GC, I addressed the PR comments so this is ready for another review, thanks in advance!

**Review by sanderson042 — APPROVED** [review]
Hi @lucianozablocki - this looks good to me. I'll approve this now. Maybe we should wait to merge this until January so nothing breaks while we are enjoying the holidays. Thanks for your work on this!

**Pull request merged**
